Abolish tg `$thing`
Abolish dt `$default`
Abolish ak `as_key`
Abolish ud undefined
Abolish df defined
Abolish ku `keep_undef`
Abolish fs false
Abolish tu true
Abolish uf `undef`
Abolish lpu Lingua::PRA::Utils
